version: '3.8'

services:
  nextapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextapp
    ports:
      - "9002:9002"
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run start
    restart: unless-stopped